version: '3.8'

services:
  frontend:
    image: node:14
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run start"
    depends_on:
      - backend

  backend:
    image: python:3.9
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: bash -c "pip install -r requirements.txt && python app.py"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
